In [1]:
from datetime import datetime

# Getting the current date and time
dt = datetime.now()

# getting the timestamp
ts = datetime.timestamp(dt)

print("Date and time is:", dt)
print("Timestamp is:", ts)

Date and time is: 2023-02-22 13:09:01.697262
Timestamp is: 1677064141.697262


In [3]:
int(datetime.timestamp(datetime.now()))

1677064184

In [4]:
import time
time.time()

1677064267.3328898

In [8]:
from datetime import datetime
dt = datetime.now()
dt.timestamp()

1677064999.068013

In [5]:
time.time_ns() // 1_000_000

1677064787938

In [12]:
import time
int(time.time()*1000000.0)

1677065138445577

In [17]:
import os.path

path = 'animal.csv'

check_file = os.path.exists(path)

print(check_file)

True


In [20]:

import numpy as np
# take data
list_d = [[1, 2, 3], [0, 0, 0], [4, 5, 6], [0, 0, 0], [7, 8, 9], [0, 0, 0]]
data = np.array(list_d)
# print original data having rows with all zeroes
print("Original Dataset")
print(data)
 
# remove rows having all zeroes
data = data[~np.all(data == 0, axis=1)]
 
# data after removing rows having all zeroes
print("After removing rows")
print(data)

Original Dataset
[[1 2 3]
 [0 0 0]
 [4 5 6]
 [0 0 0]
 [7 8 9]
 [0 0 0]]
After removing rows
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
np.unicode_(1675209605683000)

'1675209605683000'

In [39]:
C = np.full((3, 2), fill_value = ['binance','BTCUSDT'], dtype='<U7')np.full((3, 2), fill_value = ['binance','BTCUSDT'], dtype='<U7')

array([['binance', 'BTCUSDT'],
       ['binance', 'BTCUSDT'],
       ['binance', 'BTCUSDT']], dtype='<U7')

In [165]:
A = np.full((3, 2), fill_value = ['binance','BTCUSDT'], dtype='<U7')
B = np.zeros((3, 2), dtype=np.int64)
C = np.zeros((3, 4), dtype=np.float32)

np.concatenate([A,B,C], axis=1)


array([['binance', 'BTCUSDT', '0', '0', '0.0', '0.0', '0.0', '0.0'],
       ['binance', 'BTCUSDT', '0', '0', '0.0', '0.0', '0.0', '0.0'],
       ['binance', 'BTCUSDT', '0', '0', '0.0', '0.0', '0.0', '0.0']],
      dtype='<U32')

In [168]:
A = np.full((3, 2), fill_value = ['binance','BTCUSDT'], dtype='<U7')
B = np.zeros((3, 2), dtype=np.int64)
C = np.zeros((3, 4), dtype=np.float32)

res = np.rec.fromarrays([A,B,C], names='a,b,c')
res

ValueError: array-shape mismatch in array 2 ("c")

In [26]:
nlevels = 1
asks_bids_names = []
for i in range(nlevels):
    asks_bids_names.extend([f'asks[{i}].price', f'asks[{i}].amount', f'bids[{i}].price', f'bids[{i}].amount'])

header1 = ['exchange','symbol','lastupdateid','local_timestamp']

full_header = ','.join(header1 + asks_bids_names)

In [27]:

# 'exchange,symbol,lastupdateid,local_timestamp,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount'
np.savetxt('test.csv', np.concatenate([A,B,C], axis=1), delimiter=',', header=full_header, fmt='%s', comments='')

In [1]:
import numpy as np
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [2]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [54]:
from datetime import datetime


#Thursday, February 23, 2023 23:59:59
#1677196799000

#Friday, February 24, 2023 0:00:00
#1677196800000
#print(datetime.date(1677196799000).day)
print(datetime.utcfromtimestamp(1677142626.508651).day) #23
print(datetime.utcfromtimestamp(1677196799.000).day) #24 February 23, 2023 23:59:59
print(datetime.utcfromtimestamp(1677196800.000).day) #24

23
23
24


In [56]:
1677142626508651/1000_000

1677142626.508651

In [87]:
np.format_float_positional(np.float32(0.00007))

'0.00007'

In [ ]:
np.float32(0.00007).format_float_positional()

In [146]:
np.set_printoptions(suppress=True)
np.savetxt('float64.csv', [[np.float64(1.07), np.float64(1.00007)]], delimiter=',', fmt=['%.2f', '%.5f'], comments='')

In [97]:
foo = np.array([[0.01, 0.00001]], dtype=np.float32)
np.format_float_positional(foo, precision=5)

TypeError: only size-1 arrays can be converted to Python scalars

In [104]:
np.array2string(np.array([[0.01, 0.00001]], dtype=np.float32), suppress_small = True)

'[[0.01    0.00001]]'

In [105]:
np.array([[0.01, 0.00001]], dtype=np.float32)

array([[0.01   , 0.00001]], dtype=float32)

In [110]:
foo[-0:]

SyntaxError: invalid decimal literal (492764810.py, line 1)

In [123]:
np.array([[0.00007]], dtype=float)

array([[0.00007]])

In [116]:
np.array([[0.01, 0.00001]], dtype=np.float32, f='%.7f')

TypeError: array() got an unexpected keyword argument 'f'

In [120]:
np.array([[23912.97000000, 0.00001]], dtype=np.float64)

array([[23912.97   ,     0.00001]])

In [147]:
asks_bids_names = []
asks_bids_formats = []
for i in range(2):
    asks_bids_names.extend([f'asks[{i}].price', f'asks[{i}].amount', f'bids[{i}].price', f'bids[{i}].amount'])
    asks_bids_formats.extend(['%.2f', '%.5f', '%.2f', '%.5f'])
header1 = ['exchange','symbol','lastupdateid','local_timestamp']
full_header = ','.join(header1 + asks_bids_names)
#full_header = ','.join(asks_bids_names)
header1_formats = ['%s', '%s', '%g', '%g']
all_formats = header1_formats + asks_bids_formats
print(all_formats)

['%s', '%s', '%g', '%g', '%.2f', '%.5f', '%.2f', '%.5f', '%.2f', '%.5f', '%.2f', '%.5f']


In [160]:
A = np.zeros([3,2], dtype=np.float32)
B = np.zeros([3,2], dtype=np.int32)
C = np.zeros([3,2], dtype=np.float32)

res = np.rec.fromarrays([A,B,C], names='a,b,c')
res

rec.array([[(0., 0, 0.), (0., 0, 0.)],
           [(0., 0, 0.), (0., 0, 0.)],
           [(0., 0, 0.), (0., 0, 0.)]],
          dtype=[('a', '<f4'), ('b', '<i4'), ('c', '<f4')])